[package]
name = "alertmanager-webhook"
version = "0.6.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
changecase = "0.0.7"
futures-util = { version = "0.3.27", default-features = false, features = ["std"] }
hyper = { version = "0.14", features = ["full"] }
hyper-tls = "0.5.0"
opentelemetry = "0.19.0"
opentelemetry-jaeger = "0.18.0"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.100"
tokio = { version = "1.29.1", features = ["full", "tracing"] }
tracing = "0.1"
tracing-opentelemetry = "0.19.0"
tracing-subscriber = { version = "0.3", features = ["json"] }
