[package]
name = "alertmanager-webhook"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.2.1"
changecase = "0.0.7"
futures-util = { version = "0.3.24", default-features = false, features = ["std"] }
hyper = { version = "0.14", features = ["full"] }
hyper-tls = "0.5.0"
pretty_env_logger = "0.4"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.87"
tokio = { version = "1.21.1", features = ["full"] }
