[package]
name = "alertmanager-webhook"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.3.0"
changecase = "0.0.7"
futures-util = { version = "0.3.25", default-features = false, features = ["std"] }
hyper = { version = "0.14", features = ["full"] }
hyper-tls = "0.5.0"
pretty_env_logger = "0.4"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
tokio = { version = "1.22.0", features = ["full"] }
