[package]
name = "alertmanager-webhook"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.3.0"
changecase = "0.0.7"
futures-util = { version = "0.3.25", default-features = false, features = ["std"] }
hyper = { version = "0.14", features = ["full"] }
hyper-tls = "0.5.0"
opentelemetry = "0.17.0"
opentelemetry-jaeger = "0.16.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.24.1", features = ["full", "tracing"] }
tracing = "0.1"
tracing-opentelemetry = "0.17.2"
tracing-subscriber = { version = "0.3", features = ["json"] }
