---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pipeline-release-please
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "10"
    pipelinesascode.tekton.dev/on-path-changed: "[Cargo.*, src/*.rs, Containerfile]"
spec:
  params:
    - name: repo_name
      value: "{{ repo_name }}"
    - name: repo_owner
      value: "{{ repo_owner }}"
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineRef:
    params:
      - name: kind
        value: pipeline
      - name: name
        value: pipeline-release-please
      - name: namespace
        value: openshift-pipelines
    resolver: cluster
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: dockerconfig-ws
      secret:
        secretName: ghcr-io
