on:
  push:
    branches:
      - main
    paths-ignore:
      - Makefile
      - '.github/**'

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tags: "${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4
        id: release
        with:
          release-type: rust

  publish-latest:
    name: Publish latest container image
    needs: release-please
    uses: pabrahamsson/alertmanager-webhook/.github/workflows/docker-publish.yml@main

  publish-release:
    name: Publish versioned container image
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    uses: pabrahamsson/alertmanager-webhook/.github/workflows/docker-publish.yml@main
    with:
      tags: ${{ needs.release-please.outputs.tags }}
