on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      tags: "${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: rust
          package-name: alertmanager-webhook
      - run: echo "releases_created ${{ steps.release.outputs.releases_created }}"
      - run: echo "release_created ${{ steps.release.outputs.release_created }}"

  publish-latest:
    name: Publish latest container image
    needs: [release-please]
    uses: pabrahamsson/alertmanager-webhook/.github/workflows/docker-publish.yml@main

  publish-release:
    name: Publish versioned container image
    needs: [release-please]
    if: ${{ needs.release-please.steps.release.outputs.releases_created }}
    uses: pabrahamsson/alertmanager-webhook/.github/workflows/docker-publish.yml@main
    with:
      tags: ${{ needs.release-please.outputs.tags }}
